### PR TITLE
Upgrade dependencies to the lastest

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
Fix this problem https://github.com/isaacs/node-glob/issues/86 in https://github.com/gotwarlost/istanbul/issues/133

**Comment by popomore** [comment]
Why do you only test on Node 0.4 and 0.6

**Comment by mklabs** [comment]
Hello

seems good, but breaks the build on the old .travis.yml

No reason, I'm actually currently working on 0.2.x branch but it drops support to 0.8, supporting only 0.10 / 0.12

**Comment by mklabs** [comment]
I'll merge the 0.2.x branch to master, let's see if your PR can be merged then

**Pull request merged**
