### PR TITLE
Fix #13: Upgrade glob to 5.x for nodir option

### LINKED ISSUE #13: options of fileset does not support nodir option
test case: `a` directory include `ms.js` directory which contain `index.js` like this:
```
a
└── ms.js
    └── index.js
```

I only want index.js so use nodir option for [glob](https://github.com/isaacs/node-glob#options) to exclude `ms.js` directory:
```js
fileset('**/*.js', '', {nodir: true}, function(err, files) {
  console.log(files);
});
```

Expected: only print `index.js`
Actually: print `index.js` and `ms.js`

### PR DESCRIPTION
**Pull request by yurenju**

### CODE REVIEW

**Comment by yurenju** [comment]
at the end I change supported versions to 0.10 & 0.12. @mklabs, what do you think? In my opinion, support the latest two versions is reasonable.

**Comment by mklabs** [comment]
Hello @yurenju 

Sounds good to me. Thanks and sorry for the delay.

**Comment by dougwilson** [comment]
FYI releasing a patch version that drops support for runtime versions is pretty lame :(

**Comment by mklabs** [comment]
@dougwilson What do you mean ? Is it breaking anything for you ?

**Comment by dougwilson** [comment]
Yes, notably old versions of `istanbul` are no longer installable on Node.js 0.8, since they depended on `0.1.x` of this lib; it also seems like this PR was added a feature, which seems more fit for a minor version bump anyway.

**Comment by yurenju** [comment]
consider the situation which @dougwilson have, a possible solution is recall 0.1.6 and bump it to 2.0.0 but not sure if it's a proper solution for a minor change.

I also checked node-glob's [travis](https://travis-ci.org/isaacs/node-glob/) they only run test & build on node.js, 0.10, 0.12 & io.js, [istanbul](https://travis-ci.org/gotwarlost/istanbul/) run test & build on node.js 0.8, 0.10 & 0.12

**Comment by mklabs** [comment]
Thanks guys for the feedback. I'll check today if we can re-add compatibility to 0.8, considering istanbul targeting also 0.8.

It seemed like a minor change so we bump a minor version @dougwilson but you're right. I'll try to fix that later today.

**Comment by dougwilson** [comment]
> It seemed like a minor change so we bump a minor version

Yea, the minor number is the middle number :)

**Comment by mklabs** [comment]
Hi guys,

I can finally work on this issue, sorry for the delay.

@yurenju I think I'll revert your change and bump a new 0.1.x version, then reapply your commit to bump to 0.2.x

I also want to add a synchronous api, might be handy, will probably do along the 0.2.x versions

@dougwilson Thanks for the version issue and your advices, much appreciated.

**Comment by popomore** [comment]
I think you can bump 0.2.x for new version of istanbul now, and add new feature in the following version.

**Comment by dougwilson** [comment]
Thank you @mklabs I just tested that old `instanbul`s are once again installable :) I really appreciate it!

**Comment by yurenju** [comment]
Great! thanks @mklabs & @dougwilson!

**Comment by mklabs** [comment]
Thanks to both of you. It was a bit tedious but we did it! :+1: 

by the way, if you ever need it, I introduced a sync API if you have any feedbacks, they're welcome. I still need to pass in options to glob / minimatch

**Comment by popomore** [comment]
@mklabs  Have you bumped 0.2.x to npm?

**Comment by mklabs** [comment]
I should have, I didn't ?

https://www.npmjs.com/package/fileset apparently no :) I'll do that right away

**Comment by mklabs** [comment]
published

**Comment by popomore** [comment]
Great!

**Pull request merged**
