### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mklabs**

### CODE REVIEW

**Comment by ntwb** [comment]
Oh, these tests are all failing :(

**Comment by mklabs** [comment]
Yes :(

fileset needs a major rewrite. tests are flaky, and needs more work. I plan on working on it tomorrow.

**Comment by mklabs** [comment]
Reworked tests to make them pass. I'll work on releasing 2.0.2 in the afternoon.

**Comment by mklabs** [comment]
@ntwb @JJ Published as 2.0.2

**Comment by ntwb** [comment]
Awesome, thanks @mklabs 👍

**Comment by JJ** [comment]
Thanks, great job!

**Pull request merged**
