### PR TITLE
Update minimatch version

### PR DESCRIPTION
**Pull request by JJ**
To avoid warning related to DoS vuln < 3.0.2

### CODE REVIEW

**Comment by gavboulton** [comment]
+1 for this.

**Comment by ntwb** [comment]
Also +1'ing and including a link to the security advisory https://nodesecurity.io/advisories/118

**Comment by mklabs** [comment]
Hi, Thank you for the PR and the related link.

I'll try to publish today a new version.

**Comment by JJ** [comment]
Sure! Thanks for accepting it!

2016-06-25 12:40 GMT+02:00 Mickael Daniel <notifications@github.com>:

> Merged #25 <https://github.com/mklabs/node-fileset/pull/25>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mklabs/node-fileset/pull/25#event-703983039>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAAB9OES5xPJ3txRZ_mEe0ye3gbG_Qnxks5qPQW3gaJpZM4I5mQy>
> .
>



-- 
JJ

**Comment by mklabs** [comment]
No sure If I'll be able to do release today.

It requires more work than I initially expected.

**Comment by JJ** [comment]
You need help, just ask :-)

2016-06-25 13:23 GMT+02:00 Mickael Daniel <notifications@github.com>:

> No sure If I'll be able to do release today.
>
> It requires more work than I initially expected.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mklabs/node-fileset/pull/25#issuecomment-228533960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAB9OKsT-efLT1nltokBkIAF4yqBWGTks5qPQ-WgaJpZM4I5mQy>
> .
>



-- 
JJ

**Comment by mklabs** [comment]
Tests ? :)

**Comment by mklabs** [comment]
We need to update the test suite to make it pass at least.

**Comment by JJ** [comment]
Issue it and assign it to me and I'll try to do my best.

**Comment by mklabs** [comment]
sounds good to me :) Thanks a lot.

**Comment by mklabs** [comment]
Created the issue, but I cant assign you without adding you to the repo. Working on it right now.

**Comment by JJ** [comment]
I'll check it out.

2016-06-25 13:32 GMT+02:00 Mickael Daniel <notifications@github.com>:

> Created the issue, but I cant assign you without adding you to the repo.
> Working on it right now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mklabs/node-fileset/pull/25#issuecomment-228534566>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAB9Cz38SDAzk2NKisqWijmRnankuJdks5qPRHPgaJpZM4I5mQy>
> .
>



-- 
JJ

**Pull request merged**
